spring:
  application:
    name: automation
  data:
    mongodb:
      uri: mongodb+srv://${db-user}:${db-pass}@${db-host}/dpcPoc
      database: dpcPoc
clo-set:
  token: ${clo-set-token}
  group-id: ${clo-set-group-id}
  email: ${clo-set-email}
  host: ${clo-set-host}
